### ISSUE TITLE
望分享例程

### ISSUE THREAD

**Issue by ntgeralt** [maskedeken/trojan-gfw#3]
您好，感谢你制作的二进制文件。

请教一下，你用什么工具处理DNS海外解析。

**Comment by maskedeken** [comment]
如果你是在老毛子等小设备上用，一般这种设备都没有安装CA证书，会导致所有验证证书的动作都失败，可以把trojan配置文件的verify设为false。
DNS一般是用能通过TCP解析的工具，比如unbound和pdnsd，unbound还支持DoT解析

**Comment by ntgeralt** [comment]
Thank you for your reply.
